AppLoginAspCoreHL/Areas/Colaborador/Controllers/CategoriaController.cs
using AppLoginAspCoreHL.Libraries.Filtro;
using AppLoginAspCoreHL.Models.Constant;
using AppLoginAspCoreHL.Repository;
using AppLoginAspCoreHL.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppLoginAspCoreHL.Areas.Colaborador.Controllers
{
    [Area("Colaborador")]
    [ColaboradorAutorizacao]
    public class CategoriaController : Controller
    {
        
        private ICategoriaRepository _categoriaRepository;

        public CategoriaController(ICategoriaRepository categoriaRepository)
        {
            _categoriaRepository = categoriaRepository;
        }
        public IActionResult Index()
        {
            return View(_categoriaRepository.ObterTodasCategorias());
        }

        [HttpGet]
        [ValidateHttpReferer]
        public IActionResult Cadastrar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Cadastrar(Models.CategoriaLiv categoria)
        {
            if (ModelState.IsValid)
            {
                _categoriaRepository.Cadastrar(categoria);
                TempData["MSG_S"] = "Categoria salva com sucesso!";
                return RedirectToAction(nameof(Index));
            }
               return View();
        }
        [HttpGet]
        [ValidateHttpReferer]
        public IActionResult Atualizar(int id)
        {
            Models.CategoriaLiv cat = _categoriaRepository.ObterCategoria(id);
            return View(cat);
        }
        [HttpPost]
        public IActionResult Atualizar([FromForm] Models.CategoriaLiv categoria)
        {
            if (ModelState.IsValid)
            {
                _categoriaRepository.Atualizar(categoria);
                TempData["MSG_S"] = "Categoria salva com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

AppLoginAspCoreHL/Areas/Colaborador/Controllers/ClienteController.cs
using AppLoginAspCoreHL.Models.Constant;
using AppLoginAspCoreHL.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppLoginAspCoreHL.Areas.Colaborador.Controllers
{
    [Area("Colaborador")]
    [ColaboradorAutorizacao]
    public class ClienteController : Controller
    {

        private IClienteRepository _clienteRepository;
        private IEnderecoRepository _enderecoRepository;

        public ClienteController(IClienteRepository clienteRepository, IEnderecoRepository enderecoRepository)
        {
            _clienteRepository = clienteRepository;
            _enderecoRepository = enderecoRepository;
        }

        public IActionResult Index()
        {
            return View(_clienteRepository.ObterTodosClientes());
        }

        public IActionResult Endereco(int id)
        {
            return View(_enderecoRepository.ObterEndereco(id));
        }

    }
}

AppLoginAspCoreHL/Areas/Colaborador/Controllers/LivroController.cs
using AppLoginAspCoreHL.GerenciadorArquivos;
using AppLoginAspCoreHL.Libraries.Filtro;
using AppLoginAspCoreHL.Models;
using AppLoginAspCoreHL.Models.Constant;
using AppLoginAspCoreHL.Repository;
using AppLoginAspCoreHL.Repository.Contract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AppLoginAspCoreHL.Areas.Colaborador.Controllers
{
    [Area("Colaborador")]
    [ColaboradorAutorizacao]
    public class LivroController : Controller
    {
        
        private ILivroRepository _livroRepository;
        private ICategoriaRepository _categoriaRepository;


        public LivroController(ILivroRepository livroRepository, ICategoriaRepository categoriaRepository)
        {
            _livroRepository = livroRepository;
            _categoriaRepository = categoriaRepository;
        }
        public IActionResult Index()
        {
            return View(_livroRepository.ObterTodosLivros());
        }
        [HttpGet]
        [ValidateHttpReferer]
        public IActionResult Cadastrar()
        {
            IEnumerable<CategoriaLiv> listaCategoria = _categoriaRepository.ObterTodasCategorias();
            ViewBag.ListaCategorias = new SelectList(listaCategoria, "id", "nome");
            return View();
        }
        [HttpPost]
        public IActionResult Cadastrar([FromForm] Livro livro, IFormFile file)
        {
            IEnumerable<CategoriaLiv> listaCategoria = _categoriaRepository.ObterTodasCategorias();
            ViewBag.ListaCategorias = new SelectList(listaCategoria, "id", "nome");
            livro.Situacao = LivroTipoConstant.Habilitado;
            if(ModelState.IsValid)
            {
                var Caminho = GerenciadorArquivo.CadastrarImagemProduto(file);
                livro.Imagem = Caminho;
                _livroRepository.Cadastrar(livro);
                TempData["MSG_S"] = "Livro salvo com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        [ValidateHttpReferer]
        public IActionResult Atualizar(int id)
        {
            IEnumerable<CategoriaLiv> listaCategoria = _categoriaRepository.ObterTodasCategorias();
            ViewBag.ListaCategorias = new SelectList(listaCategoria, "id", "nome");
            Models.Livro liv = _livroRepository.ObterLivro(id);
            return View(liv);
        }
        [HttpPost]
        public IActionResult Atualizar([FromForm] Livro livro)
        {
            IEnumerable<CategoriaLiv> listaCategoria = _categoriaRepository.ObterTodasCategorias();
            ViewBag.ListaCategorias = new SelectList(listaCategoria, "id", "nome");
            if (ModelState.IsValid)
            {
                _livroRepository.Atualizar(livro);
                TempData["MSG_S"] = "Livro atualizado com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        [ValidateHttpReferer]
        public IActionResult EditImage(int id)
        {
            Livro liv = _livroRepository.ObterLivro(id);
            return View(liv);
        }
        [HttpPost]
        public IActionResult EditImage([FromForm] Livro livro, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var Caminho = GerenciadorArquivo.CadastrarImagemProduto(file);
                livro.Imagem = Caminho;
                _livroRepository.Atualizar(livro);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [ValidateHttpReferer]
        public IActionResult Habilitar(int Id)
        {
            _livroRepository.Habilitar(Id);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Desabilitar(int Id)
        {
            _livroRepository.Desabilitar(Id);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Detalhes(int Id)
        {
            Livro liv = _livroRepository.ObterLivro(Id);
            return View(liv);
        }

    }
}

AppLoginAspCoreHL/Areas/Colaborador/Controllers/PedidoController.cs
using AppLoginAspCoreHL.Models;
using AppLoginAspCoreHL.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppLoginAspCoreHL.Areas.Colaborador.Controllers
{
    [Area("Colaborador")]
    [ColaboradorAutorizacao]
    public class PedidoController : Controller
    {
        private IPedidoRepository _pedidoRepository;
        private IItemRepository _itemRepository;

        public PedidoController(IPedidoRepository pedidoRepository, IItemRepository itemRepository)
        {
            _pedidoRepository = pedidoRepository;
            _itemRepository = itemRepository;
        }
        public IActionResult Index()
        {
            return View(_pedidoRepository.ObterTodosPedidos());
        }
        public IActionResult FinalizarPedido(int id)
        {
            _pedidoRepository.Finalizar(id);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult ReabrirPedido(int id)
        {
            _pedidoRepository.Reabrir(id);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Detalhes(int id)
        {
            Pedido ped = _pedidoRepository.ObterPedido(id);
            int idUsu = ped.Id_usu;
            ViewData["Nm_ped"] = ped.Id_pedido;
            return View(_itemRepository.ObterTodosItensPedido(id, idUsu));
        }
    }
}

AppLoginAspCoreHL/Areas/Colaborador/Views/Shared/_Layout.cshtml
@using AppLoginAspCoreHL.Models.Constant

@inject AppLoginAspCoreHL.Libraries.Login.LoginColaborador _colaborador


<!DOCTYPE html>

<html lang="pt-br">

<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">

    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">

    <meta name="generator" content="Jekyll v3.8.5">

    <title>@ViewBag.Title</title>
    <link rel="icon" href="~/abra-o-livro.ico">

    <link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css" />

    <!-- Bootstrap core CSS -->

    <link rel="stylesheet" href="~/resources/lib/bootstrap-4.2.1-dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/resources/lib/pagedlist/PagedList.css" rel="stylesheet" type="text/css" />

    @*  <link href="~/resources/lib/pagedlist/PagedList.css" rel="stylesheet" type="text/css" /> *@

    <style>

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @@media (min-width: 768px) {

            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

    </style>

    <!-- Custom styles for this template -->

    <link href="~/resources/lib/dashboard/dashboard.css" rel="stylesheet">

</head>

<body>

    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">

        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Painel</a>

        

        <ul class="navbar-nav px-3">

            <li class="nav-item text-nowrap">

            <a class="nav-link" asp-area="Colaborador" asp-action="Logout" asp-controller="Home">Sair</a>

            </li>

           

        </ul>

    </nav>

    <div class="container-fluid">

        <div class="row">

            <nav class="col-md-2 d-none d-md-block bg-light sidebar">

                <div class="sidebar-sticky">

                    <ul class="nav flex-column">

                        <li class="nav-item">

                            <a class="nav-link active" asp-action="Painel" asp-controller="Home">

                                <span data-feather="home"></span>

                                Painel de Controle

                            </a>

                        </li>


                        <li class="nav-item">

                            <a class="nav-link" asp-action="Index" asp-controller="Categoria">

                                <span data-feather="file"></span>

                                Categoria

                            </a>

                        </li>

                        <li class="nav-item">

                            
                             <a class="nav-link" asp-action="Index" asp-controller="Livro">

                                <span data-feather="shopping-cart"></span>

                                Livros

                            </a>

                        </li>

                        @if (_colaborador.GetColaborador() != null && _colaborador.GetColaborador().Tipo == ColaboradorTipoConstant.Gerente)

                        {

                        <li class="nav-item">

                            <a class="nav-link" asp-controller="Colaborador" asp-action="Index">

                                <span data-feather="users"></span>

                                Colaborador

                            </a>

                        </li>

                         }

                        <li class="nav-item">

                            <a class="nav-link" asp-controller="Cliente" asp-action="Index">

                                <span data-feather="users"></span>

                                Cliente

                            </a>

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" asp-controller="Pedido" asp-action="Index">

                                <span data-feather="file"></span>

                                Pedidos

                            </a>

                        </li>

                    </ul>

                    @* <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">

                        <span>Saved reports</span>

                        <a class="d-flex align-items-center text-muted" href="#">

                            <span data-feather="plus-circle"></span>

                        </a>

                    </h6>

                    <ul class="nav flex-column mb-2"> *@

                        @* <li class="nav-item">

                            <a class="nav-link" href="#">

                                <span data-feather="file-text"></span>

                                Current month

                            </a>

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" href="#">

                                <span data-feather="file-text"></span>

                                Last quarter

                            </a>

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" href="#">

                                <span data-feather="file-text"></span>

                                Social engagement

                            </a>

                        </li>

                        <li class="nav-item">

                            <a class="nav-link" href="#">

                                <span data-feather="file-text"></span>

                                Year-end sale

                            </a>

                        </li> *@

                    </ul>

                </div>

            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

                @RenderBody()

            </main>

        </div>

    </div>

    <script src="~/resources/lib/jquery3.3.1/jquery-3.3.1.min.js"></script>

    <script>window.jQuery || document.write('<script src="/resources/lib/jquery3.3.1/jquery-3.3.1.min.js"><\/script>')</script>

    <script src="~/resources/lib/mask/jquery.mask.min.js"></script>

    <script src="~/resources/lib/bootstrap-4.2.1-dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/resources/lib/feather/feather.js"></script>

    <script src="~/resources/lib/charts/charts.js"></script>

    <script src="~/resources/lib/dashboard/dashboard.js"></script>

    <script src="~/resources/js/Actions.js"></script>

    <script src="~/js/site.js"></script>

</body>

</html>